info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'
dataSource:
  url: jdbc:oracle:thin:@localhost:1521/orclpdb1
  driverClassName: oracle.jdbc.OracleDriver
  dialect: org.hibernate.dialect.Oracle12cDialect
  username: linksharing
  password: 'linksharing123'
  pooled: true
  jmxExport: true
  dbCreate: create-drop
  
#dataSource:
#  url: jdbc:oracle:thin@localhost:1521/orclpdb1
#  driverClassName: oracle.jdbc.OracleDriver
#  dialect: org.hibernate.dialect.Oracle12cDialect
#  username: linksharing
#  password: 'linksharing123'
#  pooled: true
#  jmxExport: true
#  dbCreate: update
#  dbCreate: create
hibernate:
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
grails:
  plugin:
    console:
      enabled: true
  mime:
    disable:
      accept:
        header:
          userAgents:
          - Gecko
          - WebKit
          - Presto
          - Trident
    types:
      all: '*/*'
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      form: application/x-www-form-urlencoded
      html:
      - text/html
      - application/xhtml+xml
      js: text/javascript
      json:
      - application/json
      - text/json
      multipartForm: multipart/form-data
      pdf: application/pdf
      rss: application/rss+xml
      text: text/plain
      hal:
      - application/hal+json
      - application/hal+xml
      xml:
      - text/xml
      - application/xml
  views:
    gsp:
      encoding: UTF-8
      htmlcodec: xml
      codecs:
        expression: html
        scriptlet: html
        taglib: none
        staticparts: none
    default:
      codec: html
#environments:
#  development:
#    dataSource:
#      dbCreate: create-drop
#      url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE